/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mywhatsapp;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mywhatsapp.User.Contact;

/**
 *
 * @author Moham
 */
public class GroupForm extends javax.swing.JFrame {

    /**
     * Creates new form GroupForm
     */
    User me;
    IMyWhatsappServer serverRef;

    public GroupForm(User me, IMyWhatsappServer serverRef) {
        initComponents();
        this.me = me;
        this.serverRef = serverRef;
        for (Contact con : me.contacts.values()) {
            contactCB.addItem(con.Id + " : " + con.name);
        }
        contactCB.setSelectedIndex(-1);
        groupMemberTA.setText("");
        groupMemberTA.append(me.Id + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupNameTB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupMemberTA = new javax.swing.JTextArea();
        contactCB = new javax.swing.JComboBox<>();
        CreateGroupBtn = new javax.swing.JButton();
        bCastMsgTB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group & Broadcast");

        groupNameTB.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        groupMemberTA.setColumns(20);
        groupMemberTA.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        groupMemberTA.setRows(5);
        groupMemberTA.setEnabled(false);
        jScrollPane1.setViewportView(groupMemberTA);

        contactCB.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        contactCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                contactCBItemStateChanged(evt);
            }
        });

        CreateGroupBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CreateGroupBtn.setText("Create");
        CreateGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGroupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateGroupBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(groupNameTB)
                            .addComponent(contactCB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bCastMsgTB, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(groupNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCastMsgTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateGroupBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_contactCBItemStateChanged
        try {
            if (!groupMemberTA.getText().contains(contactCB.getSelectedItem().toString().trim().split(":")[0].trim())) {
                groupMemberTA.append(contactCB.getSelectedItem().toString().trim().split(":")[0].trim() + "\n");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_contactCBItemStateChanged

    private void CreateGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGroupBtnActionPerformed
        String[] memberIds = groupMemberTA.getText().split("\n");
        if (groupNameTB.isVisible()) {
            String groupName = groupNameTB.getText().trim();

            try {
                serverRef.AddGroup(groupName, memberIds);
            } catch (RemoteException ex) {
                Logger.getLogger(GroupForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            String msg = bCastMsgTB.getText().trim();
            try {
                serverRef.SendBroadCast(me.Id, memberIds, IMyWhatsappServer.MessageType.Text, msg);
            } catch (RemoteException ex) {
                Logger.getLogger(GroupForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        this.dispose();
    }//GEN-LAST:event_CreateGroupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateGroupBtn;
    public javax.swing.JTextField bCastMsgTB;
    private javax.swing.JComboBox<String> contactCB;
    private javax.swing.JTextArea groupMemberTA;
    public javax.swing.JTextField groupNameTB;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
